# 快乐喵配置文件
happyCatConfig:
  # 登录信息
  login:
    cookies: "xxx"
    # 默认UA
    DEFAULT_USER_AGENT: ""
    # 是否使用随机 useragent，默认为 false
    random_useragent: ""
  # 商品信息
  goods:
    # eid, fp参数必须填写，具体请参考 wiki-常见问题
    eid: ""
    fp: ""
    # 商品ID
    sku_id: ""
    # 设定时间 # 2020-02-24 10:00:00.100000
    buy_time: ""
  # 消息推送
  messager:
    # 使用了Server酱的推送服务
    # 如果想开启下单成功后消息推送，则将 enable 设置为 true，默认为 false 不开启推送
    # 开启消息推送必须填入 sckey，如何获取请参考 http://sc.ftqq.com/3.version。
    enable: False
    sckey: ""
